- type: job
  id: Interdyne
  name: job-name-interdyne
  description: job-description-interdyne
  playTimeTracker: JobInterdyne
  canBeAntag: false
  icon: JobIconInterdyne
  setPreference: false
  #  overrideConsoleVisibility: true # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  access: # Frontier
  - Maintenance
  - Medical
  - Chemistry
  - Paramedic
  - Interdyne
  extendedAccess: # Frontier
  - External # Frontier

- type: job
  id: InterdyneHead
  name: job-name-interdyne-head
  description: job-description-interdyne
  playTimeTracker: JobInterdyneHead
  canBeAntag: false
  icon: JobIconInterdyneHead
  setPreference: false
  #  overrideConsoleVisibility: true # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  access: # Frontier
  - Maintenance
  - Medical
  - Chemistry
  - Paramedic
  - Interdyne
  - InterdyneHead
  extendedAccess: # Frontier
  - External # Frontier
